# print('hello\nworld')

# print('hello pyth\'on')

# print("hello py\"thon")

# print('F:\uatch_8_20_PM')

# print('C:\\python\\shivani_neela')

# print("C:\\code\\program\\python")

# print('\u0001')
# print('\u0002')
# print('\u0003')
# print('\u0004')
# print('\u0005')
# print('\u0006')
# print('\u0007')
# print('\u0008')
# print('\u0009')
# print('\U0001f601')
# print('\U0001f602')
# print('\U0001f603')
# print('\U0001f604')
# print('\U0001f605')

# print("C:\\python\\program\\code\\920AM")
# print("C:\\python\program\code\920AM")

# print("hello \bworld")

# print("py\ron")
# print("pyth\ron")
# print("pythpy\ron")
# print("hello\rpy ")

# print("My Name is \r Shivani Neela")
# print("My Name is \rShivani Neela")

# print("hello\ankith")
# print("hello\aankith")
# print("hello\\ankith")
# print("hello \bnkith")
# print("hello\cnkith")
# print("hello\dnkith")
# print("hello\enkith")
# print("hello\fun")
# print("hello\gnkith")
# print("hello\hnkith")
# print("hello\inkith")
# print("hello\jnkith")
# print("hello\knkith")
# print("hello\lnkith")
# print("hello\mnkith")
# print("hello\nnkith")
# print("hello\onkith")
# print("hello\pnkith")
# print("hello\qnkith")
# print("hello\rnkith")
# print("hello\snkith")
# print("\thellonkith")
# print("hello\tnkith")
# print("hello \tnkith")
# print("hello   nkith")
# print("hello  \tnkith")
# print("hello\t nkith")
# print("hello    nkith")
# print("hello\unkith")
# print("hello\vnkith")
# print("hello\wnkith")
# print("hello\xnkith")
# print("hello\ynkith")
# print("hello\znkith")

# print("Hello\Nmberalla")
# print("Hello\Uikil")